# Generated by Django 3.1.6 on 2021-05-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.CharField(choices=[['like', 'like'], ['unlike', 'unlike']], max_length=10, verbose_name='Like'),
        ),
    ]
